### ISSUE TITLE
can't start the game

### ISSUE THREAD

**Issue by IvanKuchin** [Happyigr/Star_ship_game#1]
Looks like folders with images and sounds are missed.

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from Menu import show_go_screen, upgrade_ships
  File "c:\Users\ikuchin\Downloads\111111111\Star_ship_game\Game\Menu.py", line 3, in <module>
    from Images import *
  File "c:\Users\ikuchin\Downloads\111111111\Star_ship_game\Game\Images.py", line 37, in <module>
    meteor_images.append(pygame.image.load(path.join(img_dir, img)).convert())
FileNotFoundError: No such file or directory.

```

**Comment by IvanKuchin** [comment]
everything is good now
